apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: youtube_app
  template:
    metadata:
      labels:
        app: youtube_app
    spec:
      containers:
      - name: youtube_app
        image: mrubel/youtube_app:latest
        ports:
        - containerPort: 3000
